
# Tomcat
server:
    tomcat:
        uri-encoding: UTF-8
        threads:
          max: 1000
          min-spare: 30
    port: 8096
spring:
    application:
      name: apitest
#    mvc:
#      static-path-pattern: /static/**,/META-INFO/**
    profiles:
        active: db
    jackson:
      time-zone: GMT+8
      date-format: yyyy-MM-dd HH:mm:ss
    activiti:
#      database-schema-update: drop-create
#      database-schema-update: false
      database-schema-update: true
#      database-schema-update: create-drop
      check-process-definitions: false
#      historyLevel: none
#      historyLevel: activity
#       默认
      historyLevel: audit
#      historyLevel: full
      db-history-used: true

###########swagger2########
##接口文档
swagger:
  ##是否开启
  enable: true
  ##扫描包
  basePackage: com.controller
  ##标题
  title: baggage-客户端
  ##描述
  desc: 动态API
  ##版本
  version: 0.0.1
  ##联系方式
  contactName: mrcode
  contactUrl: mailto:mrcode@126.com
  contactEmail: mrcode@126.com

mybatis:
  mapperLocations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
